
(setf kb1 (gen-KB 5 2 3))
(setf curquery (gen-query))
(print "Iter")
(print (Test-Iter kb1 curquery))
;(print "Thread-iter")
;(print (Test-Thread-Iter kb1 newquery))
;(print "Classic")
;(print (Test-Classic kb1 newquery))
;(print "Thread-Classic")
;(print (Test-Thread-Classic kb1 newquery))
